
    pipeline{
    agent none
    
    stages {
        
        
        stage('Build') {
            environment {
              CI = 'true'
          }
          agent {
            label 'Jenkins-Cloud-Agent'
          }
            steps {
                sh 'npm install'
            }
            
        }
        
    }
    }
