
    pipeline{
    agent none
    
    stages {
        
        
        stage('Build') {
            environment {
              CI = 'true'
          }
          agent {
            label 'Jenkins-Cloud-Agent'
          }
            steps {
                sh 'npm install'
            }
            
        }
        
       stage('Build image') {
           agent {
            label 'Jenkins-Cloud-Agent'
          }
        sh "docker build --build-arg APP_NAME=sample -t 424377644605.dkr.ecr.eu-west-2.amazonaws.com/f2ride-dev-repo:latest -f Dockerfile ."
    }
    stage('Push image') {
        
        agent {
            label 'Jenkins-Cloud-Agent'
          }
        docker.withRegistry('https://424377644605.dkr.ecr.eu-west-2.amazonaws.com/f2ride-dev-repo', 'ecr:eu-west-2:AWS Cred') {
            sh "docker push 424377644605.dkr.ecr.eu-west-2.amazonaws.com/f2ride-dev-repo:latest"
        }
    }
        
    }
    }
